backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/home/home.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/"}
          - {label: "Profile Image", name: profile_image, widget: image}
          - {label: Name, name: name, widget: string}
          - {label: Position, name: position, widget: string}
          - {label: Body, name: "body", widget: "markdown"}
          - {
              label: Social,
              name: "social",
              widget: "list",
              fields: [
                {
                  label: "Social Network",
                  name: social_network,
                  widget: select,
                  options: [ 
                    { label: "Twitter", value: "twitter" },
                    { label: "Linkedin", value: "linkedin" },
                    { label: "GitHub", value: "github" },
                    { label: "Quora", value: "quora" },
                    { label: "Quora", value: "quora" },
                    { label: "Reddit", value: "reddit" },
                    { label: "Medium", value: "medium" },
                    { label: "Google", value: "google" },
                    { label: "Facebook", value: "facebook" },
                    { label: "Instagram", value: "instagram" },
                    { label: "Pinterest", value: "pinterest" },
                  ]
                },
                {
                  label: URL,
                  name: social_url,
                  widget: string
                }
              ]
            }
          - {
              label: Skills,
              name: "skills",
              widget: "list",
              fields: [
                {
                  label: "Skill name",
                  name: skill_name,
                  widget: string
                },
                {
                  label: "Skill value",
                  name: skill_value,
                  widget: number,
                  default: 5,
                  valueType: "int",
                  min: 1,
                  max: 10
                }
              ]
            }
      - file: "src/pages/about/about.md"
        label: "About (Testing)"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/product/product.md"
        label: "Products Page (Testing)"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/products"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
